#!/bin/sh

TAR_GZ=/home/khang/Downloads/nvim-linux-x86_64.tar.gz
INSTALL_PREFIX=/home/khang/Downloads/tmp

rm -f $INSTALL_PREFIX/share/icons/hicolor/128x128/apps/nvim.png
rm -fr $INSTALL_PREFIX/bin/nvim
rm -fr $INSTALL_PREFIX/lib/nvim
rm -fr $INSTALL_PREFIX/share/nvim
rm -f $INSTALL_PREFIX/share/man/man1/nvim.1

tar -xf $TAR_GZ -C $INSTALL_PREFIX --strip-components=1
