import Munkres.Mathlib.Prelude

open Set TopologicalSpace Topology

universe u

variable {α : Type u} {B : Set (Set α)}

-- If U is a set such that (for all x ∈ U, there exists some b ∈ B such that
-- x ∈ b ⊆ U), then U can be written as a union of B's elements.
lemma b3d183c (U : Set α) :
  (∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U) → ∃ s ⊆ B, U = ⋃₀ s
  := by --
  intro h
  let hp (x : U) : Set α := (h x x.prop).choose
  let s := Set.range hp
  use Set.range hp
  refine ⟨?_, ?_⟩
  · intro _ ⟨x, heq⟩
    subst heq
    exact (h x x.prop).choose_spec.1
  · rw [Set.sUnion_range]
    ext x : 1
    rw [Set.mem_iUnion]
    refine ⟨?_, ?_⟩
    · intro hx
      exact ⟨⟨x, hx⟩, (h x hx).choose_spec.2.1⟩
    · intro ⟨y, hy⟩
      exact (h y y.prop).choose_spec.2.2 hy -- ∎

/-- This is how Munkres defines the topology generated by a basis.
In particular, `𝓣 = generateFrom B` -/
theorem IsOpen_generateFrom_iff (U : Set α)
  (exists_subset_inter : ∀ t₁ ∈ B, ∀ t₂ ∈ B, ∀ x ∈ t₁ ∩ t₂, ∃ t₃ ∈ B, x ∈ t₃ ∧ t₃ ⊆ t₁ ∩ t₂)
  (sUnion_eq : ⋃₀ B = univ)
  : IsOpen[generateFrom B] U ↔ ∀ x ∈ U, ∃ b ∈ B, x ∈ b ∧ b ⊆ U
  := by --
  refine ⟨?_, ?_⟩
  · intro h x hx
    rw [Set.sUnion_eq_univ_iff] at sUnion_eq
    induction h with
    | basic b hb =>
      exact ⟨b, hb, hx, le_rfl⟩
    | univ =>
      obtain ⟨b, h⟩ := sUnion_eq x
      exact ⟨b, h.1, h.2, Set.subset_univ _⟩
    | inter u₁ u₂ _ _ hu₁ hu₂ =>
      obtain ⟨b₁, hb₁, hx₁, hu₁⟩ := hu₁ hx.1
      obtain ⟨b₂, hb₂, hx₂, hu₂⟩ := hu₂ hx.2
      specialize exists_subset_inter b₁ hb₁ b₂ hb₂ x ⟨hx₁, hx₂⟩
      obtain ⟨b, hbB, hxb, hb⟩ := exists_subset_inter
      refine ⟨b, hbB, hxb, ?_⟩
      rw [Set.subset_inter_iff] at hb ⊢
      exact ⟨hb.1.trans hu₁, hb.2.trans hu₂⟩
    | sUnion s _ hs =>
      obtain ⟨u, hus, hxu⟩ := hx
      specialize hs u hus hxu
      obtain ⟨b, hbB, hxb, hbu⟩ := hs
      refine ⟨b, hbB, hxb, ?_⟩
      refine hbu.trans ?_
      exact Set.subset_sUnion_of_subset s u le_rfl hus
  · intro h
    obtain ⟨s, hs, heq⟩ := b3d183c U h
    subst heq
    refine GenerateOpen.sUnion s ?_
    intro u hu
    exact GenerateOpen.basic u (hs hu) -- ∎
