[package]
name = "git-checkout4"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
log = { version = "0.1.0" , path = "../logger.rs" }
rayon = "1.12.0"

[dev-dependencies]
regex = "1.13.1"

[[bin]]
path = "bin/gco.rs"
name = "git-checkout4"

[lib]
doctest = false
