name: Build git-checkout2

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [
            # [latest stuff]
            ubuntu-latest,
            macos-latest,
            # [fixed versions]
            ubuntu-24.04,
            ubuntu-22.04,
            macos-15,
            macos-14,
            # [unsupported]
            # windows-latest,
            # windows-2025,
            # windows-2022,
          ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: make configure-debug
      - run: make install
      - run: make test
