[package]
name = "kopiwm"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.189"
log = { version = "0.1.0" , path = "../logger.rs" }
nix = { version = "0.31"  , features = ["signal"] }
strum = "0.28.0"
strum_macros = "0.28.0"

[build-dependencies]
bindgen = { git = "https://github.com/rust-lang/rust-bindgen", rev = "9d26c6eddeff9192ddedb563192abe3128fc5aae" }
pkg-config = "0.3.33"
