# Checks the health of the workflow YML files in this monorepo.
name: checkhealth

on:
  push:

jobs:
  checkhealth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo install --locked --force --path .
        working-directory: health
      - run: monorepo-checkhealth
