name: heliumd

on:
  push:
    paths:
      - "code/tools/wacom-macos-precision-mode-daemon/**/*"
      - .github/workflows/heliumd.yml
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-15
          - macos-14
      fail-fast: false
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - run: make build
        working-directory: code/tools/wacom-macos-precision-mode-daemon
