name: personal site

on:
  push:
    paths:
      - "code/web/site/**/*"
      - .github/workflows/personal-site.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # permissions:
    #   deployments: write
    steps:
      - uses: actions/checkout@v6

      # Pull in the blog posts.
      - name: Checkout blog posts repo (private)
        uses: actions/checkout@v6
        with:
          path: .git/blog
          repository: nguyenvukhang/blog
          token: ${{ secrets.GH_BLOGPOSTS_TOKEN }}
      - name: Copy over blog posts
        run: |
          rm -rf             code/web/site/blog
          mkdir -p           code/web/site/blog
          cp .git/blog/*.mdx code/web/site/blog || exit 0
          cp .git/blog/*.md  code/web/site/blog || exit 0
      - name: Copy over the GPG signatures
        run: |
          mkdir -p           code/web/site/public
          cp .git/blog/*.sig code/web/site/public || exit 0

      # Pull in the photos.
      - name: Checkout photos repo (public)
        uses: actions/checkout@v6
        with:
          path: .git/photos
          repository: uint2/photos
      - name: Copy over photos
        run: |
          rm -f    code/web/site/public/photos
          mkdir -p code/web/site/public/photos
          P='.git/photos'
          cp \
            $P/17e4bc091f2dee60aaf7e1e4134a7e085d403b71.png \
            $P/359f32a45b3441f2fd6393eba4ce066fd162da4b.png \
            $P/42ac53ca51b4e8b8e284c9ad9d9cf206ba44b6c8.png \
            $P/596d811785bb23a22b6f93d61bb35d476952c950.png \
            $P/614dbcf9eaaa4ad17fffee189e126d46ff73416a.png \
            $P/8dc664092ad1980fba732d9c898f11657ef0677b.png \
            $P/cd08941a1346e3f1c7d6f6662a4f9451e6bb8df7.png \
            code/web/site/public/photos

      # Compress fonts with Woff2.
      - name: Checkout google/woff2
        uses: actions/checkout@v6
        with:
          path: .git/woff2
          repository: google/woff2
          ref: 1c69169e9e1811dccd6c54c532fedda300233968
          submodules: recursive
      - name: Build woff2_compress
        working-directory: .git/woff2
        run: make clean all
      - name: Compress fonts
        working-directory: code/web/site/fonts
        run: |
          pip install fonttools==4.63.0
          WOFF2_COMPRESS='${{ github.workspace }}/.git/woff2/woff2_compress' python3 build-fonts.py

      # Build with Astro 6.
      - uses: withastro/action@v6
        with:
          path: code/web/site

      # Deploy to Cloudflare.
      - uses: cloudflare/wrangler-action@v4
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_NGUYENVUKHANGDOTCOM_API_TOKEN }}
          command: pages deploy code/web/site/dist --project-name=nguyenvukhangdotcom --branch production
          # gitHubToken: ${{ secrets.GITHUB_TOKEN }}
